= Capabilities & seccomp_filter
Felix Meulenkamp <lix@redhat.com>

== Background

.Links
* https://en.wikipedia.org/wiki/System_call
* https://man7.org/linux/man-pages/man7/capabilities.7.html
* https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt
* https://en.wikipedia.org/wiki/Linux_kernel_interfaces
* https://en.wikipedia.org/wiki/Capability-based_security#POSIX_capabilities

.Silberschatz
* ~~ABI application binary interface 82-83~~
* syscall ~22~,66-78
* ~~syscall firewall 708~~
* syscall filter (SECCOMP-BPF) 738
* capabilities ~730~,~732-733~,735-737,~747~
* capabilities protection system 735-737
* Berkeley Packet Filter (BPF) 102-104

== Script

**Teaser**

* Bist du kein root? Darfst du nichts?
* Wie entscheidet der Kernel, was dein Programm darf und was nicht?
* Und was macht da eine Firewall in meinem Kernel?

**Tagline**

* Hi, ich bin Felix Meulenkamp
* Consulting Architect für OpenShift Clouds bei Red Hat
* und ich erkläre euch in dieser Reihe Linux Security Basics

**System Calls**

System Calls oder kürzer, Syscalls, stellen die Schnittstelle für Programm auf Funktionen des Kernels dar

Damit man nicht alles ständig neu entwickeln muss nutzen Programme verschiedene Bibliotheken, sogenannte Libraries, kurz Libs, wie zB die `glibc`, die zentrale C Lib von GNU/Linux, in der verschiedene Funktionen schon fertig enthalten sind.

Brauche ich eine Eingabe oder möchte einfach nur eine Datei lesen, so kann ich die entsprechenden Funktionen aus der Bilbliothek nutzen.

Um jedoch eine Datei lesen zu können und dies nicht für jedes Dateisystem neu zu implementieren, bilden diese Bibliotheken auf die entsprechenden Syscalls des Kernels ab.

Dies schafft auch eine gewisse Unabhängigkeit von dem genauen Betriebssystem und der Architektur des Rechners.

die Libs der Programmiersprachen stellen ein stabiles Application Programming Interface, eine API, zur Verfügung und dieses verwendet dann die entsprechenden syscalls des Betriebssystems.

Es gibt Syscalls für alle möglichen Funktionen... Prozesse erzeugen und beenden, Dateien lesen und schreiben, Netzwerk Verbindungen lesen und schreiben und und und...

Verschieden Subsysteme, wie das Filesystem oder das Netzwerk werden so abstrahiert und als System Call Interfaces bezeichnet.

**Capabilities**

Da System calls tief in das System greifen, wurde früh nach einer Möglichkeit gesucht den Zugriff auf diese zu beschränken.

* Aufteilung Priviligiert vs Unpriviligiert
* weitere Aufteilung in Caps

Hierzu wurden die Capabilities eingeführt.

System Calls sind 

* Caps bündeln nach Themen
* abgabe bestimmter Caps, wenn nicht mehr benötigt
* Beispiel Apache braucht erhöhte Rechte und die Cap `CAP_NET_BIND_SERVICE` um Port 80 zu binden und gibt danach cap ab und wird zu User `Nobody`
* Vorteil Container: Nicht die Anwendung sondern die Container Run-time gibt die Caps ab
* Teil der Metadaten eines Containers in Kubernetes
* Arten von Capabilities
* Einige wichtige Beispiele
* Beschränkung 64bit deshalb Gruppierung
* xAttr `security.capability`

**Seccomp**

Grenze zwischen Kernel und User-Mode

* Syscalls sind zu grob in Caps eingeteilt
* Weitere Unterteilung dank BPF
