= Capabilities & seccomp_filter
Felix Meulenkamp <lix@redhat.com>

== Background

.Links
* https://en.wikipedia.org/wiki/System_call
* https://man7.org/linux/man-pages/man7/capabilities.7.html
* https://www.kernel.org/doc/html/latest/security/credentials.html Ebenfalls Caps
* https://en.wikipedia.org/wiki/Linux_kernel_interfaces
* https://en.wikipedia.org/wiki/Capability-based_security#POSIX_capabilities
* https://www.kernel.org/doc/html/latest/userspace-api/seccomp_filter.html

.Silberschatz
* ~~ABI application binary interface 82-83~~
* syscall ~22~,66-78
* ~~syscall firewall 708~~
* syscall filter (SECCOMP-BPF) 738
* capabilities ~730~,~732-733~,735-737,~747~
* capabilities protection system 735-737
* Berkeley Packet Filter (BPF) 102-104

== Script

**Teaser**

* Bist du kein root? Darfst du nichts?
* Wie entscheidet der Kernel, was dein Programm darf und was nicht?
* Und was macht da eine Firewall in meinem Kernel?

**Tagline**

* Hi, ich bin Felix Meulenkamp
* Consulting Architect für OpenShift Clouds bei Red Hat
* und ich erkläre euch in dieser Reihe Linux Security Basics

**System Calls**

System Calls oder kürzer, Syscalls, stellen die Schnittstelle für Programme auf Funktionen des Kernels dar

Damit man nicht alles ständig neu entwickeln muss nutzen Programme verschiedene Bibliotheken, sogenannte Libraries, kurz Libs, wie zB die `glibc`, die zentrale C Lib von GNU/Linux, in der verschiedene Funktionen schon fertig enthalten sind.

Brauche ich eine Eingabe oder möchte einfach nur eine Datei lesen, so kann ich die entsprechenden Funktionen aus der Bilbliothek nutzen.

Um jedoch eine Datei lesen zu können und dies nicht für jedes Dateisystem neu zu implementieren, bilden diese Bibliotheken auf die entsprechenden Syscalls des Kernels ab.

Dies schafft auch eine gewisse Unabhängigkeit von dem genauen Betriebssystem und der Architektur des Rechners.

die Libs der Programmiersprachen stellen ein stabiles Application Programming Interface, eine API, zur Verfügung und dieses verwendet dann die entsprechenden syscalls des Betriebssystems.

Es gibt Syscalls für alle möglichen Funktionen... Prozesse erzeugen und beenden, Dateien lesen und schreiben, Netzwerk Verbindungen lesen und schreiben und und und...

Verschieden Subsysteme, wie das Filesystem oder das Netzwerk werden so abstrahiert und als System Call Interfaces bezeichnet.


**Capabilities**

Da Syscalls tief in das System greifen, wurde früh nach einer Möglichkeit gesucht den Zugriff auf diese zu beschränken.

Deshalb wurden früh zwischen unpriviligierten und priviligierten Usern unterschieden.

Zunächst recht einfach, alles was mit effektiver UID 0 läuft ist Priviligiert und ignoriert damit alle sicherheitchecks im Kernel.

Alle anderen Nutzer waren somit von vielen Funktionen ausgesperrt.

Das Konzept wurde schliesslich um Gruppen erweitert und somit war es plötzlich auch möglich über Gruppenmitgliedschaften einige Rechte zu erlangen.

Damit nun einige harmlose Programme auf priviligierte Aktionen durchführen können wurden Konstrukte wie das SETUID- oder SETGID-Bits, auch UNIX exec privilege escalation bits, eingeführt.

Ein Programm mit einem solchen Bit gesetzt, läuft nicht unter dem Benutzer der es startet, sondern dem Benutzer, bzw. Gruppe, dem es gehört.

Damit wird es Möglich zum Beispiel den `sudo` -Befehl auch als normaler Benutzer zu nutzen, obwohl er einige Sonderrechte für das Netzwerk benötigt.

Schauen wir uns hierzu ein kurzes Beispiel an, mit dem wir Dateien finden können, welche diese Bits gesetzt haben.

Wir suchen hierbei nach Dateien, die das Bit _SETUID_, nummerisch _4000_, bzw. _SETGID_, numerisch _2000_ und dem User _root_ gehören.

.Eine schnelle Suche zeigt uns, welche Dateien diese Sonderrechte gesetzt haben.
[source,console]
----
[root@f45cd3caec65 ~]# find /usr/bin /usr/lib -perm /4000 -user root
/usr/bin/chage
/usr/bin/gpasswd
/usr/bin/newgrp
/usr/bin/mount
/usr/bin/su
/usr/bin/umount
/usr/bin/sudo
/usr/bin/pkexec
/usr/bin/passwd
/usr/bin/crontab
/usr/lib/polkit-1/polkit-agent-helper-1

[root@f45cd3caec65 ~]# find /usr/bin /usr/lib -perm /2000 -user root
/usr/bin/write
----

Dieses Konzept war jedoch immer noch leicht angreifbar, da eine Schwachstelle in einem solchen Programm nun ggfs. zu vollen Root-Rechten führte.

//In meinen frühen Jahren als Unix System Betreuer, hatte ich zum . einen Kollegen der eine ungepatchte Version des Tools `finger` regelmäßig dazu nutzte um einen Kundenserver mit wechselnden Root Passwörtern zu betreuen ohne sich jedes Mal das Passwort neu beschaffen zu müssen.

Diese extrem grobe Aufteilung reichte somit nicht aus und die Rechte wurden in Capabilities aufgeteilt.

Caps sind seit Linux 2.2 und somit seit etwa 1999 im Linux Kernel enthalten.

Eine Bit-Maske regelt welche Caps für ein Program erlaut sind und welche nicht.

Es wurden 64Bit hierfür vorgesehen, welche jedoch schnell knapp wurden.

Dies führte dazu, das die einzelnen Caps zu Gruppen wurden, die bestimmt Funktionalitäten bündeln.

Dazu gehört eine weitere Bitmaske, die regelt, wie eine Cap vererbt werden kann.

Aber Caps können nicht nur Angefordert, sondern auch abgegeben werden, wenn sie nicht mehr benötigt werden.

Das macht es zu einem wichtigen security feature.

Zum Beispiel Apache braucht erhöhte Rechte und die Cap `CAP_NET_BIND_SERVICE` um Port 80 zu binden und gibt danach die nicht weiter benötigten caps wieder ab.

Sidenote: Portnummern unter 1024 sind vertrauenswürdigen Diensten vorbehalten, weshalb man besondere Rechte braucht um einen solchen Prozess zu starten.

Wird dieser Prozess nun angegriffen, gibt es nur ein kleines Zeitfenster in dem Sonderrechte erlangt werden können.

Und noch besser, statt wie früher voll priviligiert zu sein, hat der Prozess nur noch Sonderrechte um bestimmte Netzwerkeinstellungen zu ändern.

Eine Liste der Caps gibt es in der Man Page, siehe `man 7 capabilities`.

Als Beispiel sei hier `CAP_SYS_ADMIN` angeführt, die weitreichende Privilegien im System gibt.

Oder `CAP_SYS_BOOT`, welche vereinfacht gesagt, einem Prozess erlaubt das System zu rebooten.

Immer noch sehr wichtig ist `CAP_NET_BIND_SERVICE`, welche erlaubt einen Port mit einer Portnummer kleiner 1024 zu öffnen, wie wir es schon beim Apache Webserver gesehen haben.

Überprüft werden die Berechtigungen im Kernel von dem _LSM Capabilities Module_ des  _Linux Security Module Framework (LSM)_ welches uns auch noch bei SElinux und Appamore begegnen wird.

Als ältestes Modul werden die Capabilities immer als erstes Überprüft und erst anschließend werden die weiteren Module wie SElinux abgefragt.

Die Capabilities werden immer für einzelne Threads vergeben, somit können Programme gezielt einzelne Rechte an ihre Threads vererben und privilegierte Threads von unpriveligierten isolieren.

Welche Capabilities ein Programm haben kann wird im Dateisystem abgelegt.

Moderne Linux Dateisysteme unterstützen hierfür Extended Attributes und das Attribute `security.capability` ist dafür reserviert.

**Ab hier Beispiel zeigen**

Schauen wir uns hierfür ein Beispiel auf unserer Laborumgebung an.

Zunächst muss in dieser minimalistischen Umgebung noch das Paket `attr` nachinstalliert werden.

Dies enthält das Programm `getfattr`, welches xAttribute anzeigen kann.

Das Programm `getcap` ist schon vorinstalliert.

.xAttr Beispiel für Capabilities
[source:console]
----
[root@f45cd3caec65 ~]# yum install -y attr
Updating Subscription Management repositories.
Last metadata expiration check: 0:01:21 ago on Thu 22 Oct 2020 07:33:39 PM EDT.
Dependencies resolved.
==========================================================================================================================================
 Package                 Architecture              Version                         Repository                                        Size
==========================================================================================================================================
Installing:
 attr                    x86_64                    2.4.48-3.el8                    rhel-8-for-x86_64-baseos-rpms                     68 k

Transaction Summary
==========================================================================================================================================
Install  1 Package

Total download size: 68 k
Installed size: 168 k
Downloading Packages:
attr-2.4.48-3.el8.x86_64.rpm                                                                              267 kB/s |  68 kB     00:00
------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                     265 kB/s |  68 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                  1/1
  Installing       : attr-2.4.48-3.el8.x86_64                                                                                         1/1
  Running scriptlet: attr-2.4.48-3.el8.x86_64                                                                                         1/1
  Verifying        : attr-2.4.48-3.el8.x86_64                                                                                         1/1
Installed products updated.

Installed:
  attr-2.4.48-3.el8.x86_64

Complete!

[root@f45cd3caec65 ~]# getfattr -d -m security.capability /usr/bin/*
getfattr: Removing leading '/' from absolute path names
# file: usr/bin/newgidmap
security.capability=0sAQAAAkAAAAAAAAAAAAAAAAAAAAA=

# file: usr/bin/newuidmap
security.capability=0sAQAAAoAAAAAAAAAAAAAAAAAAAAA=

# file: usr/bin/ping
security.capability=0sAAAAAgAwAAAAAAAAAAAAAAAAAAA=

[root@f45cd3caec65 ~]# getcap /usr/bin/*
/usr/bin/newgidmap = cap_setgid+ep
/usr/bin/newuidmap = cap_setuid+ep
/usr/bin/ping = cap_net_admin,cap_net_raw+p
----

**Seccomp**

Wie erwähnt sind Capabilities recht grob aufgeteilt und schützen somit recht große und überlappende *Gruppen von Systemcalls.

Capabilities wie `CAP_SYS_ADMIN` sind zudem ziemlich überladen und unspezifisch.

Dem schafft _SECure COMPuting with filters_, kurz SECCOMP BPF, abhilfe.

Durch definieren von _Berkeley Packet Filters_ können ganz gezielt einzelne Syscalls erlaubt oder verboten werden.

Dies ermöglicht eine sehr feine Kontrolle darüber, welche Kernel Funktionen erlaubt sind und welche nicht und wirkt wie eine Firewall im Kernel.

**Fazit**

Nochmal zusammengefasst:

Syscalls sind die Schnittstelle zwischen Userspace und dem Kernel um auf standartisierte Art und Weise auf Kernel Subsysteme zugreifen zu können.

Die klassische Aufteilung zwischen einem privilegierten Benutzer oder Prozess und Unprivilegierten ist viel zu grob.

Capabilities schränken diese weiter ein und ermöglichen gezielte Zugriffe auf einzelne Subsysteme.

Seccomp verfeinert die Berechtigungen mit Berkeley Packet Filters.
