= Containerisierung - Übungen
Felix Meulenkamp <lix@redhat.com>
// Metadata:
:description: Übungen zu Containerisierung
:keywords: podman, oci, docker
:license: Creative Commons Attribution-ShareAlike 4.0 International
// Settings:
:lang: de
:idprefix: id_
:source-highlighter: highlightjs
// Refs:
:url-project: https://github.com/fmeulenk/hsd-os

== Hinweis

Zur Lösung dieser Aufgaben sind die Hilfe-Seiten der Kommandos sehr hilfreich.
Das eingebaute Hilfesystem von Linux steht mit dem Befehl `man <command>` zur Verfügung.
Einige Programme stellen auch ihre  vollständige Dokumentation mit dem Befehl `info <command>` dar.
Das Kommando `man -k <Begriff>` hilft ihnen Hilfeseiten und Kommandos nach bestimmten Stichwörtern zu finden.

Alle POSIX kompatiblen Programme haben eine Option `--help`, welche eine kurze Zusammenfassung der Kommandozeilenargumente anzeigt.

== Das Lab

Öffnen sie das Lab unter https://lab.redhat.com/podman-deploy .

Im Rahmen der Übung erstellen wir einen einfachen Container mit einem Renderer für die Vorlesungsunterlagen.

Das Kommando `podman` ist container runtime engine für OCI-compatible Container.
Es ist eine Alternative zu Docker und nutzt zu großen Teilen die gleiche Kommando- und Parameterstrukturen.
Das Kommando `buildah` übernimmt dabei die Funktionalitäten eines Containerbuilds.

Mit `podman run` und anschließenden `podman commit` können einfach und schnell neue Containerimages erstellt werden.

Zur Übung wollen wir einen einfachen Webserver erstellen.


Zunächst laden wird das benötigte Image herunter.

[source,console]
----
podman pull fedora:33
----

Dies läd die einzelnen Layer des Images `docker.io/library/fedora:33` herunter und speichert sie unter `/var/lib/containers`.

Mit `podman images` können wir sehen, welche Images bereits lokal vorhanden sind.

Wir können nun aus dem Image einen Container erstellen und in diesem Software installieren

[source]
----
[root@1b0a838cf4f5 $]# podman run -ti fedora:33
[root@58f03d2910c9 /]#
----

Wir sehen das der Hostname sich ändert.
Das Parameter `-ti` steht für TTY anhängen (`-t`) und Interactiver Modus (`-i`), welche zu einem Parameter zusammen gezogen wurden, wie es unter dem Posix-Standard für Kurz-Parameter erlaubt ist.

Nun installieren wir das Tool Asciidoctor und ein paar Plugins.

[source]
----
yum -y install gem && yum clean all
gem asciidoctor asciidoctor-pdf asciidoctor-revealjs rouge
mkdir /data
exit
----

Das `&& yum clean all` bewirkt, das nach der erfolgreichen Installation direkt alle ge-cache-ten Datein wieder gelöscht werden.
Es ist im Interaktiven Mode nicht so wichtig dies direkt in einem Kommando zu vereinen, jedoch in einem `RUN`-Statement eines Containerbuilds, wäre dies so üblich, um zu verhindern, dass für die zwischengespeicherten RPM-Datein ein Layer angelegt wird.

Mit `exit` wurde der Container wieder verlassen.
Da kein `--rm` beim `podman run` gesetzt wurde, bleibt der Container erhalten und kann mit `podman ps -a` gelistet werden.

Wir erzeugen nun ein neues Image aus dem gestoppten Container.
Hierfür listen wir ihn und benutzen dann `podman commit` um ihn unter dem Namen `ad:latest` zu speichern.

[source]
----
podman commit -c WORKDIR=/data <container_name | id> ascii:latest
----

Die Option `-c WORKDIR=/data` sorgt dafür, dass das Arbeitsverzeichnis aud `/data` gesetzt wird.

Mit `podman images` kann man sich alle lokalen Images anzeigen lassen.

Als nächstes Clonen wir das Git-Repository mit den Vorlesungsunterlagen.

[source]
----
git clone https://github.com/fmeulenk/hsd-os.git
cd hsd-os
----

Nun können das frische Image nutzen um die AsciiDoc Dateien in HTML und PDF Datein zu übersetzen.

[source]
----
podman run --rm -v$PWD:/data:z ascii asciidoctor-pdf -a allow-uri-read *.adoc
podman run --rm -v$PWD:/data:z ascii asciidoctor-revealjs \
  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2  *_slides.adoc
----

Nun fehlt uns leider ein Web-Browser in der Lab-Umgebung.
Jedoch haben wir ein Lab mit Port-Umleitung für den Port 8081

Das das Image auch Phyton enthält, können wir einfach einen kleinen Webserver starten.

[source]
----
podman run --rm -v$PWD:/data:z -p 8081:8000/tcp ascii python3 -m http.server
----

Jetzt können wir uns die Seiten über den Reiter "Container Service" anschauen.
